language: python

python:
  - "3.7"

install:
  - pip install black coverage coveralls h5py isort mypy numba numpy phantomconfig scipy tomlkit

script:
  - python -m coverage run -m pytest
  - isort --check-only -rc phantomsetup tests
  - black --check --skip-string-normalization phantomsetup tests
  # - mypy --no-strict-optional --ignore-missing-imports phantomsetup tests

after_success:
  - coveralls

notifications:
  email:
    recipients: d.mentiplay@gmail.com
    on_success: change
    on_failure: always
