channels:
  - conda-forge
dependencies:
  - python>=3.7
  - sphinx
  - ipykernel
  - jupytext
  - nbsphinx
  - numpy
  - matplotlib
  - pip:
    - git+https://github.com/dmentipl/phantom-setup.git@master
